[build]
  command    = "npm ci && npx vite build && npx esbuild netlify/functions/api.ts --bundle --platform=node --target=node18 --external:@neondatabase/serverless --external:express-session --external:connect-pg-simple --external:bcrypt --external:jsonwebtoken --external:ws --format=esm --outdir=netlify/functions"
  publish    = "dist/public"
  functions  = "netlify/functions"

[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/api/:splat"
  status  = 200

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200