[build]
  command    = "npm ci && npm run migrate && npm run build:frontend && npm run build:functions"
  publish    = "dist/public"
  functions  = "netlify/functions"
  
[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/api/:splat"
  status  = 200

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
